trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Billing Processing'
    organization: 'icarotorres'
    scannerMode: 'MSBuild'
    projectKey: 'IcaroTorres_rabbitmq-billing-processing'
    projectName: 'rabbitmq-billing-processing'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll, **/*.*Tests/**,**/DependencyInjection/*.cs
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: |
      "**/ScheduledProcessing/Library.csproj"
      "**/ScheduledProcessing/Customers.Api.csproj"
      "**/ScheduledProcessing/Issuance.Api.csproj"
      "**/ScheduledProcessing/Processing.Worker.csproj"
      "**/ScheduledProcessing/Library.UnitTests.csproj"
      "**/ScheduledProcessing/Customers.Api.UnitTests.csproj"
      "**/ScheduledProcessing/Issuance.Api.UnitTests.csproj"
      "**/ScheduledProcessing/Processing.Worker.UnitTests.csproj"
    verbosityRestore: Quiet

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
      "**/ScheduledProcessing/Library.csproj"
      "**/ScheduledProcessing/Customers.Api.csproj"
      "**/ScheduledProcessing/Issuance.Api.csproj"
      "**/ScheduledProcessing/Processing.Worker.csproj"
      "**/ScheduledProcessing/Library.UnitTests.csproj"
      "**/ScheduledProcessing/Customers.Api.UnitTests.csproj"
      "**/ScheduledProcessing/Issuance.Api.UnitTests.csproj"
      "**/ScheduledProcessing/Processing.Worker.UnitTests.csproj"
    arguments: '--configuration $(BuildConfiguration) --no-restore /p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'

- task: VSTest@2
  inputs:
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SimondeLang.sonarcloud-buildbreaker.sonar-buildbreaker.sonarcloud-buildbreaker@2
  displayName: 'Break build on quality gate failure'
  inputs:
    SonarCloud: 'Sonar Billing Processing'
    organization: 'icarotorres'


