name: ci-quality-gate

trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'
  demands: java
  
steps:

- task: UseDotNet@2
  displayName: Use dotnet sdk 
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    includePreviewVersions: true
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Billing Processing'
    organization: 'icarotorres'
    projectKey: 'IcaroTorres_rabbitmq-billing-processing'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '-c Release --no-restore' 

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/UnitTests.csproj'
    arguments: '-c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  
- task: SimondeLang.sonarcloud-buildbreaker.sonar-buildbreaker.sonarcloud-buildbreaker@2
  displayName: 'Break build on quality gate failure'
  inputs:
    SonarCloud: 'Sonar Billing Processing'
    organization: 'icarotorres' 
