name: ci-azure-pipelines

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  azure-devops-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/icarostuart/RabbitMQ%20Billing%20Processing'
        azure-pipeline-name: 'ci-sonarcloud'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
