name: ci-build
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
 
jobs:
  build:
    name: Build and Test 
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Restore
        run: nuget restore ScheduledProcessing/ -NoCache
    
      - name: Build
        run: dotnet build ScheduledProcessing/ -c Release --no-restore

      - name: Test
        run: dotnet test ScheduledProcessing/ -c Release --no-build --filter Tests.csproj