name: Billing Processing CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build-and-test:
  
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2          
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      
      - name: Restore
        run: dotnet restore ScheduledProcessing/
      
      - name: Build
        run: dotnet build ScheduledProcessing/ -c Release
        
      - name: Test
        run: dotnet test ScheduledProcessing/ -c Release
