name: Billing Processing CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.13
      
      - name: Build with dotnet
        run: dotnet build --c Release
        
      - name: Run tests
        run: dotnet test --c Release  
